### ISSUE TITLE
ROG-STRIX-Z590-A-i710700KF-RX5700XT-Hackintosh

### ISSUE THREAD

**Issue by BrockChen** [cuihairu/ROG-STRIX-Z590-A-i910900K-RX6900XT-Hackintosh#2]
When first installed and config completed, it can boot up the ethernet. After then I reboot, not ethernet found.

![IMG_2719](https://user-images.githubusercontent.com/3970030/201512897-eaa8ae4f-6bca-48d3-84a0-40010dce2b25.JPG)

**Comment by cuihairu** [comment]
[I225_stock_vs_cstmfw](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md#readme)
This might help you

-  Ventura removed AppleIntelI210Ethernet.kext, so you need to make sure that AppleIntelI210Ethernet.kext exists in your `EFI/OC/Kexts` directory.
-  you need to add `e1000=0` to the boot parameters

`EFI/OC/config.plist`:

```xml
<key>Kernel</key>
	<dict>
		<key>Add</key>
		<array>
		<dict>
			<key>Arch</key>
			<string>Any</string>
			<key>BundlePath</key>
			<string>AppleIntelI210Ethernet.kext</string>
			<key>Comment</key>
			<string></string>
			<key>Enabled</key>
			<true/>
			<key>ExecutablePath</key>
			<string>Contents/MacOS/AppleIntelI210Ethernet</string>
			<key>MaxKernel</key>
			<string></string>
			<key>MinKernel</key>
			<string></string>
			<key>PlistPath</key>
			<string>Contents/Info.plist</string>
		</dict>
		</array>
	</dict>	
<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>ForceDisplayRotationInEFI</key>
				<integer>0</integer>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args</key>
				<string>keepsyms=1 debug=0x100 npci=0x2000 watchdog=0  e1000=0 -lilubetaall</string>
				<key>csr-active-config</key>
				<data>7w8AAA==</data>
				<key>prev-lang:kbd</key>
				<string>zh-Hans:252</string>
				<key>run-efi-updater</key>
				<string>No</string>
			</dict>
		</dict>
         </dict>
```

**Comment by BrockChen** [comment]
> [I225_stock_vs_cstmfw](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore/blob/main/I225_stock_vs_cstmfw.md#readme) This might help you
> 
> * Ventura removed AppleIntelI210Ethernet.kext, so you need to make sure that AppleIntelI210Ethernet.kext exists in your `EFI/OC/Kexts` directory.
> * you need to add `e1000=0` to the boot parameters
> 
> `EFI/OC/config.plist`:
> 
> ```
> <key>Kernel</key>
> 	<dict>
> 		<key>Add</key>
> 		<array>
> 		<dict>
> 			<key>Arch</key>
> 			<string>Any</string>
> 			<key>BundlePath</key>
> 			<string>AppleIntelI210Ethernet.kext</string>
> 			<key>Comment</key>
> 			<string></string>
> 			<key>Enabled</key>
> 			<true/>
> 			<key>ExecutablePath</key>
> 			<string>Contents/MacOS/AppleIntelI210Ethernet</string>
> 			<key>MaxKernel</key>
> 			<string></string>
> 			<key>MinKernel</key>
> 			<string></string>
> 			<key>PlistPath</key>
> 			<string>Contents/Info.plist</string>
> 		</dict>
> 		</array>
> 	</dict>	
> <key>NVRAM</key>
> 	<dict>
> 		<key>Add</key>
> 		<dict>
> 			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
> 			<dict>
> 				<key>ForceDisplayRotationInEFI</key>
> 				<integer>0</integer>
> 				<key>SystemAudioVolume</key>
> 				<data>Rg==</data>
> 				<key>boot-args</key>
> 				<string>keepsyms=1 debug=0x100 npci=0x2000 watchdog=0  e1000=0 -lilubetaall</string>
> 				<key>csr-active-config</key>
> 				<data>7w8AAA==</data>
> 				<key>prev-lang:kbd</key>
> 				<string>zh-Hans:252</string>
> 				<key>run-efi-updater</key>
> 				<string>No</string>
> 			</dict>
> 		</dict>
>          </dict>
> ```

cool. Thanks!

**Comment by BrockChen** [comment]
But another problem, Autdio not work (Audio device f0c8)

**Comment by cuihairu** [comment]
- Try to fix USB port mapping
    [OS-X-USB-Inject-All](https://github.com/RehabMan/OS-X-USB-Inject-All)
    If your computer motherboard is the same as my computer motherboard is Asus z590, you can use my repair file (USBInjectAll-ASUS-Z590-A-Gaming.kext).
  `config.plist`-`Kernel.Add`:
   ```xml
      <dict>
		<key>Arch</key>
		<string>Any</string>
		<key>BundlePath</key>
		<string>USBInjectAll-ASUS-Z590-A-Gaming.kext</string>
		<key>Comment</key>
		<string></string>
		<key>Enabled</key>
		<true/>
		<key>ExecutablePath</key>
		<string>Contents/MacOS/USBInjectAll</string>
		<key>MaxKernel</key>
		<string></string>
		<key>MinKernel</key>
		<string></string>
		<key>PlistPath</key>
		<string>Contents/Info.plist</string>
	</dict>
   ```

<img width="284" alt="image" src="https://user-images.githubusercontent.com/3733908/201638099-ad39c176-3d3f-46da-8f1b-6c07d0c91ec2.png">


-  Try to inject the sound card id 
   [AppleALC](https://github.com/acidanthera/AppleALC/releases)

**Comment by BrockChen** [comment]
Thanks for reply. 
I use you newest release, but the problem still there.

My motherboard is ROG-STRIX-Z590-A-WIFI not WIFI II.

**Comment by cuihairu** [comment]
- [AppleALC Support codecs ](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)
- [Audio support](https://dortania.github.io/hackintosh/updates/2021/04/24/rocket-lake.html)

ROG-STRIX-Z590-A-WIFI This motherboard integrated sound card is ALC4080, this sound card uses the USB protocol, AppleALC driver does not yet support this sound card. You just need to fix the USB to enable this sound card.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/3733908/204005032-83a16468-0cd5-4ee1-9d39-2c62716e8857.png">

- [Usb fix](https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit)
- [Chinese Tutorial](https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-1.html)

**Comment by BrockChen** [comment]
Thanks, that's worked.
