### ISSUE TITLE
同样配置，核显输出黑屏。

### ISSUE THREAD

**Issue by Lasx** [cuihairu/ROG-STRIX-Z590-A-i910900K-RX6900XT-Hackintosh#4]
同样配置，核显输出黑屏。用的n卡，屏蔽独立显卡后，会黑屏。貌似不行。不知道注入EDID会不会有解

**Comment by cuihairu** [comment]
集成显卡可以参考iGPU分支的配置，我没有N卡，无法测试，如果是13系统那么应该N卡支持不好。

**Comment by Lasx** [comment]
我查了一下Z590 10代cpu核显基本上都是黑屏无输出

**Comment by cuihairu** [comment]
我测试了下，只有UHD630是黑屏，找了下资料看到有[驱动UHD630 10代U+HDMI的视频教程](https://www.bilibili.com/video/BV1UW4y1J7J2/?spm_id_from=autoNext&vd_source=f147a968fae499ab942dfc3645b8fcb9)，测试了注入EDID的方式发现只有DP线没有成功我目前帮不了忙。

**Comment by Lasx** [comment]
算了，我还是换张卡吧。买个6600xt去
